[k3s_servers]
master01 ansible_host=100.109.138.26 ansible_user=ronoa ansible_python_interpreter=/usr/bin/python3.12

[k3s_agents]
master02 ansible_host=100.114.145.104 ansible_user=ronoa ansible_python_interpreter=/usr/bin/python3.12
worker01 ansible_host=100.119.230.76 ansible_user=ronoa ansible_python_interpreter=/usr/bin/python3.12

[k3s_cluster:children]
k3s_servers
k3s_agents
