---
- name: Mise à jour OS — Workers
  hosts: k3s_agents
  serial: 1
  become: true

  tasks:
    - name: Drain le nœud
      become: false
      delegate_to: localhost
      ansible.builtin.command: >
        kubectl drain {{ inventory_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --disable-eviction=true
        --timeout=180s
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"

    - name: Mise à jour des paquets
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        autoremove: true

    - name: Vérifier si reboot nécessaire
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot si nécessaire
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists

    - name: Uncordon le nœud
      become: false
      delegate_to: localhost
      ansible.builtin.command: kubectl uncordon {{ inventory_hostname }}
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"

    - name: Attendre Ready
      become: false
      delegate_to: localhost
      ansible.builtin.command: >
        kubectl wait node {{ inventory_hostname }}
        --for=condition=Ready
        --timeout=120s
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
      changed_when: false

- name: Mise à jour OS — Control plane
  hosts: k3s_servers
  serial: 1
  become: true

  tasks:
    - name: Mise à jour des paquets
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        autoremove: true

    - name: Vérifier si reboot nécessaire
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot si nécessaire
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists
